import { loadEnv } from "@codexsun/framework/env";
import { z } from "zod";

const envSchema = z.object({
  NODE_ENV: z.enum(["development", "test", "staging", "production"]).default("development"),
  AUTH_MODE: z.enum(["cookie", "jwt", "hybrid"]).default("jwt"),
  PLATFORM_API_PORT: z.coerce.number().int().positive(),
  PLATFORM_API_URL: z.string().url("PLATFORM_API_URL must be a valid URL"),
  PLATFORM_WEB_PORT: z.coerce.number().int().positive().default(7080),
  PLATFORM_WEB_ORIGIN: z.string().url("PLATFORM_WEB_ORIGIN must be a valid URL"),
  PLATFORM_WEB_ORIGINS: z.string().default(""),
  PLATFORM_WEB_HEALTH_URL: z.union([z.literal(""), z.string().url()]).default(""),
  DB_HOST: z.string().default("127.0.0.1"),
  DB_PORT: z.coerce.number().int().positive(),
  DB_USER: z.string().min(1, "DB_USER is required"),
  DB_PASSWORD: z.string(),
  DB_DRIVER: z.enum(["mariadb", "mysql2"]).default("mariadb"),
  TRADES_DB_NAME: z.string().min(1, "TRADES_DB_NAME is required").default("trades_db"),
  TRADES_DB_FRESH_ON_START: z.enum(["0", "1"]).default("0"),
  TRADES_DB_RESET_CONFIRM: z.string().default(""),
  TRADES_ALLOW_PRODUCTION_DB_RESET: z.enum(["0", "1"]).default("0"),
  TRADES_BACKUP_DIR: z.string().default("storage/backups/database"),
  TRADES_QUEUE_BACKEND: z.enum(["database", "bullmq-redis"]).default("database"),
  TRADES_QUEUE_COMPLETED_RETENTION_DAYS: z.coerce.number().int().positive().default(14),
  TRADES_QUEUE_FAILED_RETENTION_DAYS: z.coerce.number().int().positive().default(30),
  TRADES_QUEUE_WORKER_ENABLED: z.enum(["0", "1"]).default("1"),
  TRADES_QUEUE_WORKER_INTERVAL_MS: z.coerce.number().int().positive().default(5000),
  TRADES_REDIS_URL: z.string().min(1, "TRADES_REDIS_URL is required"),
  TRADES_ALLOW_LIVE_RESTORE: z.enum(["0", "1"]).default("0"),
  TRADES_LIVE_RESTORE_CONFIRM: z.string().default(""),
  TRADES_RESTORE_TEST_DB_NAME: z.string().default(""),
  TRADES_VERIFIED_BACKUP_ID: z.string().default(""),
  ENABLE_SINGLE_CLIENT: z.enum(["0", "1"]).default("1"),
  DEV_AUTO_CLIENT_LOGIN: z.enum(["0", "1"]).default("0"),
  CLIENT_DOMAIN_BASE: z.string().default("localhost"),
  CLIENT_ADMIN_EMAIL: z.string().default(""),
  CLIENT_ADMIN_NAME: z.string().default(""),
  CLIENT_ADMIN_PASSWORD: z.string().default(""),
  CLIENT_CORPORATE_ID: z.string().default("TRADES"),
  CLIENT_DOMAIN: z.string().default("app.trades.test"),
  CLIENT_NAME: z.string().default("Trades"),
  CLIENT_SLUG: z.string().default("trades"),
  JWT_SECRET: z.string().min(1, "JWT_SECRET is required"),
  SOFTWARE_ADMIN_EMAIL: z.string().default(""),
  SOFTWARE_ADMIN_NAME: z.string().default(""),
  SOFTWARE_ADMIN_PASSWORD: z.string().default(""),
  SUPER_ADMIN_EMAIL: z.string().default(""),
  SUPER_ADMIN_NAME: z.string().default(""),
  SUPER_ADMIN_PASSWORD: z.string().default(""),
  STORAGE_PUBLIC_ROOT: z.string().default("storage/public"),
  STORAGE_ROOT: z.string().default("storage/app")
});

export const env = loadEnv(envSchema);
